# Generated by Django 3.2.9 on 2021-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_tokencounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencounter',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
