# Generated by Django 3.2.9 on 2021-12-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_tokencounter_token_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Content',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='data',
            name='URL',
            field=models.CharField(default='', max_length=70),
        ),
    ]
